credentials:
  usernames:
    kolbotn:
      name: Kolbotn IL
      password: $2b$12$AueM1zINKakEgkist0ufK.Oks0c1YtqzEhXkrvZOXiH.qODXUaKM2 # To be replaced with hashed password
    basum:
      name: Båsum Boring
      password: $2b$12$QZ1rYv3nU4vd/H6Ti/kP/.TYo41vA4WjkcbbTSADJb8ChK.oma5Qa # To be replaced with hashed password
    asplanviak:
      name: Asplan Viak
      password: $2b$12$gqvYW7PEYOEMvYY5gQDbyOJEdqzUgNrNjIltb99EO50tF/qVa6HUi # To be replaced with hashed password
cookie:
  expiry_days: 60
  key: some_signature_key
  name: some_cookie_name
