credentials:
  usernames:
    kolbotn:
      name: Kolbotn IL
      password: $2b$12$D8uUJWCVbVpq29kX/54hquGYI3oRxesyW/kthAv.22w4OhBepVl22 # To be replaced with hashed password
    basum:
      name: Båsum Boring
      password: $2b$12$zh07eQA6Gtwl98yzIqH3bOQMspYzQdjChA5q5xTm0RmWzUqdftdgS # To be replaced with hashed password
    asplanviak:
      name: Asplan Viak
      password: $2b$12$V/lh0cC6rj2HIpW38UWIDudq0PGpLt59XUjGBweMIsgfxaJT02N7m # To be replaced with hashed password
cookie:
  expiry_days: 60
  key: some_signature_key
  name: some_cookie_name
