credentials:
  usernames:
    kolbotn:
      name: Kolbotn IL
      password: $2b$12$z/og1JnlDd/bqwF.PA5/x.6RXFU0yhUCE4mkjVxjPukQqNAEPEuy. # To be replaced with hashed password
    asplanviak:
      name: Asplan Viak
      password: $2b$12$zwddFY4mU4gtv6sGXv/pjeqzdoUGdQoRV2L/614JOs7jylpq1h8Qe # To be replaced with hashed password
cookie:
  expiry_days: 60
  key: some_signature_key
  name: some_cookie_name
